roboboat_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

#roboboat_velocity_controller:
#  type: "diff_drive_controller/DiffDriveController"
#  left_wheel: ['front_left_wheel', 'rear_left_wheel']
#  right_wheel: ['front_right_wheel', 'rear_right_wheel']
#  publish_rate: 50
#  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
#  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
#  cmd_vel_timeout: 0.25
#  velocity_rolling_window_size: 2

  # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Husky hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.2   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2
