odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 50

odom0: zed/zed_node/odom
odom0_config: [true, true, false,
              false, false, true,
              true, true, false,
              false, false, false,
              false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, true, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

use_control: false # set true tominclude cmd_velmin estimation
